apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-api
  template:
    metadata:
      labels:
        app: mobile-api
    spec:
      containers : 
        - name : mobile-api-app
          image : gcr.io/lateral-rider-383313/IMAGE_NAME_MOBILE_API:TAG
          imagePullPolicy: Always
        