apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers : 
        - name : web-api-app
          image : gcr.io/lateral-rider-383313/IMAGE_NAME_WEB_API:TAG
          imagePullPolicy: Always
        